
package com.test.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import com.test.Book;
import com.test.BookArray;
import com.test.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BookService", targetNamespace = "http://test.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BookService {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://test.com/BookService/addBookRequest", output = "http://test.com/BookService/addBookResponse")
    public boolean addBook(
        @WebParam(name = "arg0", partName = "arg0")
        Book arg0);

    /**
     * 
     * @return
     *     returns com.test.BookArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://test.com/BookService/getAllBooksRequest", output = "http://test.com/BookService/getAllBooksResponse")
    public BookArray getAllBooks();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://test.com/BookService/deleteBookRequest", output = "http://test.com/BookService/deleteBookResponse")
    public boolean deleteBook(
        @WebParam(name = "arg0", partName = "arg0")
        Book arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.test.Book
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://test.com/BookService/getBookRequest", output = "http://test.com/BookService/getBookResponse")
    public Book getBook(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

}
